spring:
  datasource:
    url: ${DB_PATH}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: ${ACCESS_EXPIRATION}
    refresh-expiration: ${REFRESH_EXPIRATION}

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    grant-type: authorization_code
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    redirect-uri: ${KAKAO_REDIRECT_URI}
